language: python
before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
install:
    - conda create -n testenv --yes pip python=2.7
    - source activate testenv
    - conda install --yes --quiet numpy=1.8 scipy=0.16 scikit-learn=0.18 matplotlib=1.3 scikit-optimize=0.1
    - conda install --yes --quiet mne joblibs pandas nose coverage
    - pip install -q flake8
    - pip install coverage coveralls
    - python setup.py install
script:
    - nosetests . --with-coverage
    - flake8 --count autoreject
